### PR TITLE
STUD-1290 Release Fixing version to match workiva convention

### PR DESCRIPTION
**Pull request by joecotton-wk**
## Purpose

This PR addresses STUD-1290. The version was hardcoded and not being automatically increased, which means that future releases would have the same version 😬 

## Solution

The solution is to configure Rosie's settings to tag and release on every merge to master. This follows Workiva convention, and also allows us to auto increment the version every time a merge is made.

## Semantic Versioning (check one)

- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
    - *[link to the breaking change in the diff]*
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
  release

## How to QA

- [ ] run the following related examples: **(fill in)**
- [ ] Other necessary steps needed to fully exercise the solution should be added here. **(fill in)**

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
<details>
<summary>(6) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>com.fasterxml.jackson.core:jackson-databind < 2.12.6.1</code> via <code>java/pom.xml</code></li>
<li>1 vulns in <code>com.google.guava:guava</code> via <code>java/pom.xml</code> with no fix reported by GitHub</li>
<li>1 vulns in <code>commons-io:commons-io < 2.7</code> via <code>java/pom.xml</code></li>
<li>1 vulns in <code>junit:junit < 4.13.1</code> via <code>java/pom.xml</code></li>
<li>2 vulns in <code>mysql:mysql-connector-java < 8.0.28</code> via <code>java/pom.xml</code></li>
<li>3 vulns in <code>com.h2database:h2 < 2.1.210</code> via <code>java/pom.xml</code></li>
</details>

## Action Items
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=anaplan-java-client">this Splunk dashboard</a> for more CVE details
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by jimgriffith-wk — APPROVED** [review]
Approving following conversation in slack regarding the origin of the `-SNAPSHOT` nomenclature.

**Comment by jimgriffith-wk** [comment]
QA +1 The artifact generated in the build looks right to me!

**Comment by joecotton-wk** [comment]
@Workiva/release-management-p

**Pull request merged**
