### PR TITLE
RM-154298 Release 1.4.5

### PR DESCRIPTION
**Pull request by joecotton-wk**
## Purpose

Release for STUD-804.

Includes:

* #18 

## Solution

High level overview of what was done. This is the roadmap for those who are going to CR.

## Semantic Versioning (check one)

- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
    - *[link to the breaking change in the diff]*
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
  release

## How to QA

- [ ] run the following related examples: **(fill in)**
- [ ] Other necessary steps needed to fully exercise the solution should be added here. **(fill in)**

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(6) Vulnerable direct dependencies were detected</summary>
<li>1 vulns in <code>com.fasterxml.jackson.core:jackson-databind < 2.12.6.1</code> via <code>java/pom.xml</code></li>
<li>1 vulns in <code>com.google.guava:guava</code> via <code>java/pom.xml</code> with no fix reported by GitHub</li>
<li>1 vulns in <code>commons-io:commons-io < 2.7</code> via <code>java/pom.xml</code></li>
<li>1 vulns in <code>junit:junit < 4.13.1</code> via <code>java/pom.xml</code></li>
<li>2 vulns in <code>mysql:mysql-connector-java < 8.0.28</code> via <code>java/pom.xml</code></li>
<li>3 vulns in <code>com.h2database:h2 < 2.1.210</code> via <code>java/pom.xml</code></li>
</details>
<details>
<summary>(2) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
<li>Watched keyword <code>BUILD_ARTIFACTS_VERACODE</code> in <code>Dockerfile</code> line(s) ['25'] added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Review dependencies for available updates
* See <a href="https://splunk.workiva.net/en-US/app/search/security_vulnerable_dependencies?form.repository=anaplan-java-client">this Splunk dashboard</a> for more CVE details
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by joewaters-wf — APPROVED** [review]
+10
- All component PRs QA reviewed

**Comment by joewaters-wf** [comment]
@Workiva/release-management-p for merge

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
